name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: test  # Optional: if you want to explicitly wait for CI to finish, use "needs: test" if your CI job is named 'test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}             # e.g., ec2-13-61-175-50.eu-north-1.compute.amazonaws.com
          username: ${{ secrets.SERVER_USER }}         # e.g., ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}          # Your EC2 private key (contents of instance2.pem)
          script: |
            cd /home/ubuntu/fastapi-book-project2
            git pull origin main
            git reset --hard origin/main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi
            sudo systemctl restart nginx
